split:
  test_size: 0.2
  random_state: 42

model:
  n_estimators: [300, 500, 600]
  max_depth: [null, 20, 30]
  min_samples_split: [2, 5]
  min_samples_leaf: [1, 2]
  max_features: [sqrt, log2]
  cv: 3
  random_state: 42

